### ISSUE TITLE
Appears way too early in curriculum

### ISSUE THREAD

**Issue by sammarcus** [learn-co-curriculum/simple-math#11]
Has this always been this early in the curriculum? It should be much later, after it explains what variables and arguments are as these have not even been addressed prior to this lab in the current position that it is right now.
cc @SophieDeBenedetto 
![image](https://cloud.githubusercontent.com/assets/8689264/9101340/8b32dfa0-3bb3-11e5-8257-38c37d7a2c72.png)

**Comment by AnnJohn** [comment]
Issue was fixed. Closing
