### ISSUE TITLE
Tagged in Learn as a Reading, not a Lab

### ISSUE THREAD

**Issue by markedwardmurray** [learn-co-curriculum/simple-math#7]
This repo is tagged as a reading in Learn and only about half of the students have turned it in as a lab (32/57). Is there a way to change this in the YAML without destroying student progress, @spencer1248 @SophieDeBenedetto ?

**Comment by changamanda** [comment]
+1 to this on the Web Dev 2015 track

**Comment by AnnJohn** [comment]
Iceboxing for now

**Comment by SophieDeBenedetto** [comment]
this has been fixed from a while ago.
